lint:
  nextflow_config:
  - params.input
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Marc P. Hoeppner
  description: Annotation of metazoan genomes
  force: false
  is_nfcore: true
  name: genomeannotator
  org: nf-core
  outdir: .
  version: 1.0dev
